name: Node.js CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Commit build artifacts
      run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add dist/*
          git commit -m "Update build artifacts" || echo "No changes to commit"
          git push
